version: "3.9"

services:
  alexa-skill:
    build: ./alexa-skill
    container_name: alexa-skill
    env_file: .env
    ports:
      - "9000:8080"
    depends_on:
      - music-assistant-api

  music-assistant-api:
    build: ./music-assistant-api
    container_name: music-assistant-api
    env_file: .env
    ports:
      - "8099:8099"